ciscoecosystem/aci-go-client

- client/infraNodeBlk_service.go
- models/infra_node_blk.go
added model and service files for infraNodeBlk
> Cacit 46 add new resource infra node blk

- client/fvRsDomAtt_service.go
- client/vmmSecP_service.go
- models/fv_rs_dom_att.go
- models/vmm_sec_p.go
added models and service file for fvrsdomatt and vmmsecp
> CACIT-47 Added models and service files

- client/fvRsDomAtt_service.go
> CACIT-47 updated service file

- client/client.go
This diff provides an option to skip logging REST request payload,
since some payloads contain credentials.
> Adding an option to skip logging request payload

- client/infraGeneric_service.go
- client/infraRsFuncToEpg_service.go
- models/infra_generic.go
- models/infra_rs_func_to_epg.go
added two new resource infraGeneric and infraRsFuncToEpg
> CACIT-54 models and service files added

- client/vnsRedirectDest_service.go
- client/vnsSvcRedirectPol_service.go
- models/vns_redirect_dest.go
- models/vns_svc_redirect_pol.go
two new resource added for classes: vnsSvcRedirectPol, vnsRedirectDest.
> CACIT-56 model and service files added

- client/vnsRedirectDest_service.go
- client/vnsSvcRedirectPol_service.go
> renaming done

- client/infraFexBndlGrp_service.go
- client/infraFexP_service.go
- client/infraRsAccBaseGrp_service.go
- models/infra_fex_bndl_grp.go
- models/infra_fex_p.go
- models/infra_rs_acc_base_grp.go
Three new resource added for classes: infraFexP, infraFexBndlGrp, infraRsAccBaseGrp
> CACIT-57 model and service files added

- client/cloudCtxProfile_service.go
- models/cloud_prov_p.go
checked in azure and updated accordingly.
> Cacit 59 check on azure

- client/infraRsSpAccPortP_service.go
- client/infraSpAccPortGrp_service.go
- client/infraSpAccPortP_service.go
- client/infraSpineP_service.go
- client/infraSpineS_service.go
- models/infra_rs_sp_acc_port_p.go
- models/infra_sp_acc_port_grp.go
- models/infra_sp_acc_port_p.go
- models/infra_spine_p.go
- models/infra_spine_s.go
added 5 new resources for classes: infraSpAccPortGrp, infraSpAccPortP, infraRsSpAccPortP, infraSpineP, infraSpineS.
> Cacit 60 add spine leaf objects

- client/fabricPathEp_service.go
- models/fabric_path_ep.go
added datasource for class fabricPathEp.
> Cacit 69 add ds for fabric path ep

- client/fabricHIfPol_service.go
- models/fabric_h_if_pol.go
added resource for fabricHlfPol
> CACIT-74 model and service file added

- client/aaaDomain_service.go
- models/aaa_domain.go
added new resource for aaaDomain
> CACIT-79 model and service file added

- client/vzAny_service.go
- models/cloud_subnet.go
name added in cloud_subnet resource.
> name added in cldSubnet

- client/vnsAbsGraph_service.go
- models/vns_abs_graph.go
added resource for class vnsAbsGraph
> vnsABSGraph model added

- client/vnsLDevCtx_service.go
- models/vns_l_dev_ctx.go
added resource for class vnsLDevtoCtx
> Cacit 91 add resource for vns l dev ctx

- client/vnsAbsNode_service.go
- models/vns_abs_node.go
> Models and service files Added

- client/vnsLIfCtx_service.go
- models/vns_l_if_ctx.go
Class Names: vnsLIfCtx
Resource Name: aci_logical_interface_context
> Cacit 93 vns l if ctx

- client/cloudRegion_service.go
- client/cloudRouterP_service.go
- client/dhcpOptionPol_service.go
- client/dhcpOption_service.go
- client/vnsLIfCtx_service.go
- models/cloud_router_p.go
- models/dhcp_option.go
- models/dhcp_option_pol.go
- models/vns_l_if_ctx.go
Class Names: dhcpOptionPol and dhcpOption
Resource Name: aci_dhcp_option_policy and aci_dhcp_option
> Cacit 152 dhcp option

- client/dhcpLbl_service.go
- models/dhcp_lbl.go
added service and model files for dhcpLbl
> Cacit 369 dhcplbl

- client/dhcpRelayP_service.go
- models/dhcp_relay_p.go
dhcpRelayP
Branch: CACIT-153-dhcp-relay-p
> Cacit 153 dhcp relay p

- client/client.go
- client/infraBrkoutPortGrp_service.go
- models/infra_brkout_port_grp.go
> 257 infra brkout port grp

- client/bgpRtSummPol_service.go
- client/l3extIp_service.go
- models/bgp_rt_summ_pol.go
- models/l3ext_ip.go
CACIT-1100 added service and model files of bgpRtSummPol.
> CACIT-1093/1100 added service and model files of l3extIp & bgpRtSummPol.

- client/bgpPeerPfxPol_service.go
- client/l3extLoopBackIfP_service.go
- client/ospfIfP_service.go
- models/bgp_peer_pfx_pol.go
- models/l3ext_loop_back_if_p.go
- models/ospf_if_p.go
Add resource ospfifp, l3extloopbackifp and bgppeerpfxpol
> Add resource ospf if p l3ext loop back if p bgp peer pfx pol

- client/bgpCtxPol_service.go
- models/bgp_ctx_pol.go
> CACIT-1469 service and model file added

- client/bgpCtxAfPol_service.go
- models/bgp_ctx_af_pol.go
service and model file added for BGPctxAfPol
> CACIT-1470 service and model file added

- client/ipNexthopP_service.go
- client/ipRouteP_service.go
- models/ip_nexthop_p.go
- models/ip_route_p.go
CACIT-2193 added model and service file of ipNexthopP.
> CACIT-2192 added model and service file of ipRouteP.

- client/stpIfPol_service.go
- models/base_attributes.go
- models/name_alias_attribute.go
- models/stp_if_pol.go
New files to be added:
1. stpIfPol_service
2. stp_if_pol
> Class - stpIfPol model and client files

- client/client.go
Fix for proxies with authentication
> proxy_URL logic updated

- client/aaaDomainRef_service.go
- models/aaa_domain_ref.go
Note:
Added module and service file to map Tenant Security Domain using aaaDomainRef class.
> Added module and service file to map Tenant Security Domain

- client/aaaDomainRef_service.go
- models/aaa_domain_ref.go
Note:
Removed description attribute from module and service file.
> Removed description attribute from aaa_domain_ref module

- .gitignore
Note:
Added Git Ignore file to avoid Project settings files and other IDE files.
> Added Git Ignore file to avoid Project settings files

- client/rtctrlAttrP_service.go
- models/rtctrl_attr_p.go
Note:
Regenerated the rtctrlAttrP model and service files.
Cleaning the rtctrlAttrP model before adding below functionalities:
> - Set communities
> - Set preferences
> - Additional Communities
> Updated rtctrlAttrP model with current coding standard

- client/bgpProtP_service.go
- models/bgp_prot_p.go
add relationship bgpRsBestPathCtrlPol in l3out bgp protocol profile
move nameAlias to L3outBGPProtocolProfile NameAliasAttribute
> add relationship in bgp_protp

- client/bgpProtP_service.go
return tDn instead of tnBgpBestPathCtrlPolName
> [bugfix] fix readRelationbgpRsBestPathCtrlPot

- client/rtctrlMatchCommFactor_service.go
- client/rtctrlMatchCommTerm_service.go
- models/rtctrl_match_comm_factor.go
- models/rtctrl_match_comm_term.go
and it's child community factor rtctrlMatchCommFactor
> Added new class object for match_rules community terms [rtctrlMatchCommTerm]

- client/rtctrlSetTag_service.go
- models/rtctrl_set_tag.go
Note:
Created rtctrlSetTag model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Created rtctrlSetTag model and service file

- client/rtctrlSetWeight_service.go
- models/rtctrl_set_weight.go
Note:
Created rtctrlSetWeight model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Created rtctrlSetWeight model and service file

- client/rtctrlSetRtMetric_service.go
- models/rtctrl_set_rt_metric.go
Note:
Created rtctrlSetRtMetric model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Created rtctrlSetRtMetric model and service file

- client/rtctrlSetRtMetricType_service.go
- models/rtctrl_set_rt_metric_type.go
Note:
Created rtctrlSetRtMetricType model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetRtMetricType model and service file

- client/rtctrlSetDamp_service.go
- models/rtctrl_set_damp.go
Note:
Created rtctrlSetDamp model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetDamp model and service file

- client/rtctrlSetComm_service.go
- models/rtctrl_set_comm.go
Note:
Created rtctrlSetComm model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetComm model and service file

- client/rtctrlSetAddComm_service.go
- models/rtctrl_set_add_comm.go
Note:
Created rtctrlSetAddComm model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetAddComm model and service file

- client/rtctrlSetNh_service.go
- models/rtctrl_set_nh.go
Note:
Created rtctrlSetNh model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetNh model and service files

- client/rtctrlSetNhUnchanged_service.go
- client/rtctrlSetRedistMultipath_service.go
- models/rtctrl_set_nh_unchanged.go
- models/rtctrl_set_redist_multipath.go
Note:
Created rtctrlSetNhUnchanged, rtctrlSetRedistMultipath - model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetNhUnchanged, rtctrlSetRedistMultipath - model and service files

- client/rtctrlSetASPathASN_service.go
- client/rtctrlSetASPath_service.go
- models/rtctrl_set_as_path.go
- models/rtctrl_set_as_path_asn.go
- models/rtctrl_set_tag.go
- models/rtctrl_set_weight.go
Note:
Created rtctrlSetASPath, rtctrlSetASPathASN - model and service file. PR belongs to the story: https://github.com/CiscoDevNet/terraform-provider-aci/issues/826
> Added rtctrlSetASPath, rtctrlSetASPathASN - model and service files

- client/vzRsFiltAtt_service.go
- models/vz_rs_filt_att.go
for both directions (consumer_to_provider and provider_to_consumer)
> [minor_changes] added new class object vzRsFiltAtt to add filters

- client/fvEpAnycast_service.go
- client/fvEpNlb_service.go
- client/fvEpReachability_service.go
- client/ipNexthopEpP_service.go
- models/fv_ep_anycast.go
- models/fv_ep_nlb.go
- models/fv_ep_reachability.go
- models/ip_nexthop_ep_p.go
Note:
Added fvEpReachability and ipNexthopEpP models and client files. PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/531
> Added fvEpReachability and ipNexthopEpP models and client files

- client/client.go
fixes #856 from terraform aci repository: https://github.com/CiscoDevNet/terraform-provider-aci/issues/856
> [minor_change] error output change from client do functions

- client/leakInternalSubnet_service.go
- client/leakTo_service.go
- models/leak_internal_subnet.go
- models/leak_to.go
Note:
Added models to create EPG/BD subnet leak internal subnet, PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/554
> Added models for the leak internal subnet

- client/fvnsMcastAddrBlk_service.go
- client/fvnsMcastAddrInstP_service.go
- models/fvns_mcast_addr_blk.go
- models/fvns_mcast_addr_inst_p.go
go client code for multicast address pools
> [minor change] multicast address pools

- client/infraAccBndlGrp_service.go
- client/infraAccNodePGrp_service.go
- client/infraSpineAccNodePGrp_service.go
Note:
Updated below service files to return valid target DN value:
infraAccBndlGrp_service.go
infraAccNodePGrp_service.go
infraSpineAccNodePGrp_service.go
PR related to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/776
> Updated service files to return valid target DN value

- client/cloudCtxProfile_service.go
- models/cloud_ctx_profile.go
Note:
Added VpcGroup attribute and removed relational attributes from CloudContextProfile, PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/678
> Added VpcGroup attribute and removed relational attributes from CloudContextProfile

- models/cloud_subnet.go
Note:
Added Subnet Group Label to the CloudSubnet model PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/677
> Added Subnet Group Label to the CloudSubnet model

- client/vnsBackupPol_service.go
- client/vnsL1L2RedirectDest_service.go
- models/vns_backup_pol.go
- models/vns_l1_l2_redirect_dest.go
Note:
Added policy based redirect models and client files. PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/941
> Added policy based redirect models and client files

- client/l3extInstP_service.go
- client/l3extSubnet_service.go
- models/l3ext_inst_p.go
Note:
Added tDn to l3extInstP service - l3extRsInstPToProfile object read function and updated model file with constant values, PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/956
> Added tDn to l3extInstP service - l3extRsInstPToProfile object read function

- client/dhcpRelayGwExtIp_service.go
- models/dhcp_relay_gw_ext_ip.go
Note:
Created the model and client file for the class: dhcpRelayGwExtIp, PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/961
> Added DHCP Relay Gateway model and client file

- client/fabricPortConfig_service.go
- client/infraPortConfig_service.go
- models/fabric_port_config.go
- models/infra_port_config.go
Note:
Added Interface Configuration model and service files, PR belongs to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/1012
> Added Interface Configuration model and service files

- models/infra_port_config.go
Note:
Removing the assocGrp to configure the BrkoutMap
> Added logic to reset assocGrp while creating BrkoutMap

- client/bfdMhIfP_service.go
- models/bfd_mh_if_p.go
under L3out -> Logical Node Profile ->  Logical Interface Profiles -> BFD Multihop
> [minor_changes] Added new resource for BFD multihop (object: bfdMhIfP).

- client/psuInstPol_service.go
- models/psu_inst_pol.go
Hi,
This PR is created to add support for CRUD operations for psu:InstPol which is missing. This is one of the resources I'm missing so for now I need to use "aci_rest" resource to have this configured. Because of that - this is not addressed under the "Issues" tab here. (Should I create an Issue describing a resource I want to implement before starting working on it?)
Please carry out the review, thank you.
Mateusz
> Added support for psu:InstPol

- client/bfdMhIfP_service.go
- client/bfdMhIfPol_service.go
- models/bfd_mh_if_p.go
- models/bfd_mh_if_pol.go
Added resources for bfdMhIfPol to support the relationship of bfdMhIfP object. Made the ReadRelationbfdRsMhIfPol() return tDn instead of name.
> Added new resource BFD Multihop Interface Policy

- client/client.go
- models/vns_abs_func_conn.go
Note:
Added PostObjectConfig function to the client.go file to handle the nested object configuration.
And added DeviceLIfName to the vns_abs_func_conn.go, model.
> Added PostObjectConfig function to the client.go file

- client/service_manager.go
- models/vns_abs_func_conn.go
Added connType attribute to vns_abs_func_conn.go file and added a condition in service_manager.go file to check if the error message is '202-Request in progess'.
> [minor_changes] Added connType attribute to vns_abs_func_conn.go file

- client/l3extDefaultRouteLeakP_service.go
- models/l3ext_default_route_leak_p.go
Note:
PR belong to: https://github.com/CiscoDevNet/terraform-provider-aci/issues/977
> Added l3extDefaultRouteLeakP model and client file

- client/client.go
Fix skipLoggingPayload usage in Authenticate to avoid data race condition issues.
Issue - CiscoDevNet/terraform-provider-aci#1218
> [minor_change] Fix skipLoggingPayload usage in Authenticate 

- models/fv_ctx.go
> Added two attributes to fvCtx

- models/fv_ae_pg.go
> [minor_changes] added pc_tag attribute to fvAEPg

- models/fv_bd.go
> Added seg attribute to fvBD

- client/client.go
Tested by running a plan to create 1000 tenants. Without re-auth it fails with 403 with the new change the plan will complete.
> [bugfix] Relogin and retry API call when 403 received due to token expired. (DCNE-507)
